//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargosService.DataAccess.Contract.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.Crews = new HashSet<Crew>();
        }
    
        public System.Guid Id { get; set; }
        public string Brand { get; set; }
        public string RegistrationNumber { get; set; }
        public int Year { get; set; }
        public int Payload { get; set; }
        public double FuelConsumption { get; set; }
        public double Volume { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crew> Crews { get; set; }
    }
}
